(function () {
    'use strict';
    //配置路由
    angular.module('sydbApp')
        .config(['$controllerProvider', '$compileProvider', '$filterProvider', '$provide', function ($controllerProvider, $compileProvider, $filterProvider, $provide) {
            var myApp = angular.module('sydbApp');
            // lazy controller, directive and service
            myApp.controller = $controllerProvider.register;
            myApp.directive = $compileProvider.directive;
            myApp.filter = $filterProvider.register;
            myApp.factory = $provide.factory;
            myApp.service = $provide.service;
            myApp.constant = $provide.constant;
            myApp.value = $provide.value;
        }])
        .factory("LOAD_DEMAND", LOAD_DEMAND);
    function LOAD_DEMAND() {
        return {
            //demo
            'demoNew': [
              'app/assistsInnovation/demo/d1.controller.js'
            ],
            //助力创新
            'assistsInnovation': [
                'app/assistsInnovation/index/index.controller.js',
                'app/assistsInnovation/index/index.service.js'
            ],
            //知产求购
            'knowledgeBuy':[
                'app/assistsInnovation/knowledgeBuy/buyIP.service.js',
                'app/assistsInnovation/knowledgeBuy/buyIP.controller.js',
                ],
            'buyIP':[
                'app/assistsInnovation/knowledgeBuy/buyIP.controller.js',
                'app/assistsInnovation/knowledgeBuy/buyIP.service.js'
            ],
            //发布知产求购
            'publishBuyIP':[
                'app/assistsInnovation/knowledgeBuy/publishBuyIP.controller.js',
            ],
            //知产求购详情
            'buyIPDetails':[
                'app/assistsInnovation/knowledgeBuy/BuyIPDetails.controller.js',
            ],
            //知产出售
            'knowledgeSales':[
                'app/assistsInnovation/knowledgeSales/saleIP.service.js',
                'app/assistsInnovation/knowledgeSales/saleIP.controller.js',
            ],
            //获取知产出售详情
            'saleIPDetails':[
                'app/assistsInnovation/knowledgeSales/SaleIPDetails.controller.js'
            ],
            //发布知产出售
            'publishSaleIP':[
                'app/assistsInnovation/knowledgeSales/publishSaleIP.controller.js'
            ],
            //融资推荐列表
            'financingRecommendation':[
                'app/assistsInnovation/financingRecommendation/financingRecommendation.controller.js',
                'app/assistsInnovation/financingRecommendation/financingRecommendation.service.js'
            ],
            //设备库
            'deviceLibrary':[
                'app/assistsInnovation/deviceLibrary/deviceLibrary.controller.js',
                'app/assistsInnovation/deviceLibrary/deviceLibrary.service.js',
            ],
            //设备详情
            'deviceLibraryDetail':[
                'app/assistsInnovation/deviceLibrary/deviceLibraryDetail.controller.js',
                'app/assistsInnovation/deviceLibrary/deviceLibraryDetail.service.js',
                'app/assistsInnovation/deviceLibrary/applyDeviceLibrary.controller.js',
            ],
            //项目解读
            'projectInterpretation':[
                'app/assistsInnovation/projectInterpretation/projectInterpretation.controller.js'
            ],
            //项目讲座
            'projectLecture':[
                'app/assistsInnovation/projectLecture/projectLecture.controller.js'
            ],
            //专家推荐
            'expertInterpretation':[
                'app/assistsInnovation/expertInterpretation/expertInterpretation.controller.js',
                'app/assistsInnovation/expertInterpretation/expertInterpretation.service.js',
                'app/assistsInnovation/expertInterpretation/expertContactModal.controller.js'
            ],
            //专家成果
            'expertAchievement':[
                'app/assistsInnovation/expertAchievement/expertAchievement.controller.js',
                'app/assistsInnovation/expertAchievement/expertAchievement.service.js'
            ],
            //项目申报
            'projectDeclaration':[
                'app/assistsInnovation/projectDeclaration/projectDeclaration.controller.js',
                'app/assistsInnovation/projectDeclaration/projectBouncesModal.controller.js',
                'layouts/notLoginModal/notLoginModal.controller.js'
            ],

            //专业解读
            'professionalInterpretation':[
                'app/assistsInnovation/professionalInterpretation/professionalInterpretation.controller.js',
                'app/assistsInnovation/professionalInterpretation/professionalInterpretation.service.js'
            ],
            //发布融资需求
            'publishNeed':[
                'app/assistsInnovation/financingRecommendation/publishNeed.controller.js',
                'app/assistsInnovation/financingRecommendation/publishNeed.service.js'
            ],
            //技术融资
            'financingDetail':[
                'app/assistsInnovation/financingRecommendation/financingDetail.controller.js',
                'app/assistsInnovation/financingRecommendation/financingDetail.service.js'
            ],
            //项目解读详情
            'projectInterpretationDetail':[
                'app/assistsInnovation/projectInterpretation/projectInterpretationDetail.controller.js'
            ],
            //项目讲座详情
            'projectLectureDetail':[
                'app/assistsInnovation/projectLecture/projectLectureDetail.controller.js'
            ],
            //项目申报详情
            'projectDeclarationDetail':[
                'app/assistsInnovation/projectDeclaration/projectDeclarationDetail.controller.js'
            ],
            //专家解读详情
            'professionalInterpretationDetail':[
                'app/assistsInnovation/professionalInterpretation/professionalInterpretationDetail.controller.js',
                'app/assistsInnovation/professionalInterpretation/professionalInterpretation.service.js'
            ],
            //专家成果详情
            'expertAchievementDetail':[
                'app/assistsInnovation/expertAchievement/expertAchievementDetail.controller.js',
                'app/assistsInnovation/expertAchievement/expertAchievement.service.js'
            ],
            //专家库详情
            'expertInterpretationDetail':[
                'app/assistsInnovation/expertInterpretation/expertInterpretationDetail.controller.js',
                'app/assistsInnovation/expertInterpretation/expertInterpretation.service.js',
                'app/assistsInnovation/expertInterpretation/expertContactModal.controller.js'
            ],
            //场地列表
            'fieldsList':[
                'app/assistsProject/fieldDetail/field.service.js',
                'app/assistsProject/fieldDetail/field.controller.js'
            ],
            //场地列表详情
            'fieldDetail':[
                'app/assistsProject/fieldDetail/fieldDetail.controller.js'
            ],
            //活动列表
            'ActivitiesList':[
                'app/assistsProject/activityDetail/activity.controller.js',
                'app/assistsProject/activityDetail/activity.service.js'
            ],
            //活动列表详情
            'ActivityDetail':[
                'app/assistsProject/activityDetail/activityDetail.controller.js'
            ],
            //助力创业
            'assistsProject':[
                'app/assistsProject/index/index.controller.js',
                'app/assistsProject/index/index.service.js'
            ],
            //培训机构
            'trainingDetail':[
                'app/assistsProject/trainingDetail/trainingDetail.controller.js',
                'app/assistsProject/trainingDetail/trainingDetail.service.js'
            ],
            //培训机构详情
            'viewTrainingDetail':[
                'app/assistsProject/trainingDetail/viewTrainingDetail.controller.js',
                'app/assistsProject/trainingDetail/trainingDetail.service.js'
            ],
            //路演活动
            'activityDetail':[
                'app/assistsProject/activityDetail/activityDetail.controller.js'
            ]
            ,
            //路演活动详情
            'viewActivityDetail':[
                'app/assistsProject/activityDetail/viewActivityDetail.controller.js'
            ],
            //创业指导
            'projectGuidance':[
                'app/assistsProject/projectGuidance/projectGuidance.controller.js',
                'app/assistsProject/projectGuidance/projectGuidance.service.js',
                'app/assistsProject/projectGuidance/projectGuidanceBounces.controller.js',
                'layouts/notLoginModal/notLoginModal.controller.js'
            ],
            //沈阳基地
            'shenyangBase':[
                'app/assistsProject/shenyangBase/shenyangBase.controller.js',
                'app/assistsProject/shenyangBase/shenyangBase.service.js',
                'app/assistsProject/shenyangBase/shenyangBaseBounces.controller.js',
                'app/assistsProject/shenyangBase/shenyangBaseModal.controller.js',
                'layouts/notLoginModal/notLoginModal.controller.js'
            ],
            //入驻企业
            'settledEnterprise':[
                'app/assistsProject/settledEnterprise/settledEnterprise.controller.js',
                'app/assistsProject/settledEnterprise/settledEnterprise.service.js'
            ],
            //入驻企业详情
            'settledEnterpriseDetail':[
                'app/assistsProject/settledEnterprise/settledEnterpriseDetail.controller.js',
                'app/assistsProject/settledEnterprise/settledEnterprise.service.js'
            ],
            //知产评估
            'knowledgeAssess':[
                'app/assistsInnovation/knowledgeAssess/assess.service.js',
                'app/assistsInnovation/knowledgeAssess/knowledgeAssess.controller.js',
                'app/assistsInnovation/knowledgeAssess/knowledgeAssessApply.controller.js'
            ],
            //登录
            'login':[
                'app/login/login.controller.js',
                'app/login/login.service.js'
            ],
            //注册
            'register':[
                'app/register/register.controller.js',
                'app/register/register.service.js'
            ],
            //企业中心
            'personalCenter':[
                'app/personalCenter/layout/layout.controller.js',
                'app/personalCenter/basicData/basicData.controller.js',
                'app/personalCenter/basicData/basicDataModal.controller.js',
                'app/personalCenter/basicData/enterpriseCertification.controller.js',
                'app/personalCenter/basicData/basicData.service.js',
                'app/personalCenter/basicData/enterpriseCertificationPassModal.controller.js',
                'app/personalCenter/basicData/enterpriseCertificationSubmitModal.controller.js'

            ],
            //我的收藏
            'collections':[
                'app/personalCenter/collections/collections.controller.js',
                'app/personalCenter/collections/collections.service.js'
            ],
            //我的知产
            'knowledge':[
                'app/personalCenter/knowledge/knowledge.controller.js',
                'app/personalCenter/knowledge/knowledge.service.js'
            ],
            //我的融资
            'financing':[
                'app/personalCenter/financing/financing.controller.js',
                'app/personalCenter/financing/financing.service.js'
            ],
            //我的申报
            'declare':[
                'app/personalCenter/declare/declare.controller.js',
                'app/personalCenter/declare/declare.service.js'
            ],
            //修改密码
            'modifyPassword':[
                'app/personalCenter/modifyPassword/modifyPassword.controller.js',
                'app/personalCenter/modifyPassword/modifyPassword.service.js'
            ],
            //忘记密码（第一步）
            'forgetPassword':[
                'app/forgetPassword/forgetPassword.controller.js',
                'app/forgetPassword/forgetPassword.service.js',
            ],
            //安全验证（第二步）
            'securityValidate':[
                'app/forgetPassword/securityValidate.controller.js',
                'app/forgetPassword/forgetPassword.service.js',
            ]
            ,//重置密码（第三步）
            'repeatPassword':[
                'app/forgetPassword/repeatPassword.controller.js',
                'app/forgetPassword/forgetPassword.service.js',
            ]
            ,//找回密码成功（第四步）
            'findPasswordSuccess':[
            'app/forgetPassword/findPasswordSuccess.controller.js',
            'app/forgetPassword/forgetPassword.service.js',
        ]
        }
    }

})();
